apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: will-playground-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/m3L4n/mpochard-config.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    syncOptions:
      - CreateNamepace=true
    automated:
      selfHeal: true
      prune: true
