apiVersion: v1
kind: Service
metadata:
  app: wil-playground
  name: wil-service
spec:
  type: ClusterIP
  selector:
    app: wil-playground
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
