apiVersion: v1
kind: Service
metadata:
  app: wil-playground
  name: wil-service
spec:
  type: ClusterIP
  selector:
    app: wil-playground
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
